### PR TITLE
Full Guide to make the bot 

### PR DESCRIPTION
**Pull request by Artiume**
not sure if you want this in the ReadMe, a different link or dont want it at all, but I thought I would give back some for the awesome bot :)

### CODE REVIEW

**Comment by KGT1** [comment]
hey thanks. I think its good to have it in the readme i was just too lazy:)

**Comment by KGT1** [comment]
can you maybe remove the discordjs.guide links? i dont think those are needed after this.

**Comment by Artiume** [comment]
sure, I'll remove them. i can also add a few more images for the jellyfin and discord side of the house.

**Comment by Artiume** [comment]
a few things i've noticed in the behavior, you actually dont need to summon the bot to make it accept commands, summon just allows it to appear as a device in jellyfin. If you invite the bot then immediately tell it to play a song, it will (albeit, it's a bit buggy like the total playtime of the song won't appear) join the voice channel you're in and start playing. Perhaps ?Connect would be better than ?Summon ? Just some food for thought. 

I want to test it some more, but with multiple bots, i gave each one a profile on jellyfin. I was also running out of browsers for sessions haha. I tried creating a private browser window, summon the bot, casted to the bot and then closed the browser window without any ill effects that i can see so far.

**Comment by KGT1** [comment]
but the summon command also summons the bot into your channel.

The playlist issue is most definitely on the bots side.I didn't even know you could edit the playlist on the fly haha.
POST request doing what?

**Comment by Artiume** [comment]
could argue ?connect 'connects' the bot to your channel, i dunno, now that I understand what's happening, it isn't too difficult but I was a n00b to both discord and the bot so I had to fumble my way through everything haha.  My friend and I want to connect this python program to the bot. We send a url to the bot and the bot sends it to the python. Especially since what's happened recently this week, we just want to make it a personal fork and not something to contribute back to your bot. 

https://gist.githubusercontent.com/oddstr13/351b7ae52a92703212652168437d08ce/raw/b82fc46a4f1b30fcb1e03af9c381963ed4b6c3e9/http_ytdl.py

**Comment by KGT1** [comment]
So without knowing to much python I'm guessing you want the bot to play youtube content?
Why not use a dedicated youtube bot?

**Comment by Artiume** [comment]
it's pulling the content to the server directly, id also like to minimize the total number of bots haha

**Comment by KGT1** [comment]
this would probably require a whole rewrite of playbackmanager and some other parts, besides adding a http server to handel the post requests. The Problem is this bot is relatively strictly tied down to jellyfin and if youd want to play content outside of it youd have to rewrite much of the code.


_I personally dont like when discord bots try do expand their feature set out of their inital scope( example: https://github.com/Aaronidk/Dorito-bot-discord.js(NSFW)) and try to become a moderation bot besides being a music bot etc. While i do understand the simplicity of just having one bot for everything, id recommend setting up a second bot for your other content._

**Pull request merged**
